export const data = [
  {
    id: 1,
    image: "/images/static/Product-photo.jpg",
    title: "کابل تبدیل USB به لایتنینگ پینزی مدل L6 طول 1 متر",
    alt: "Product",
    price: 60000,
    discount: 20,
    available: true,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 120000 },
    ],
  },
  {
    id: 2,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ 15 اینچی لنوو مدل Ideapad",
    alt: "Product",
    price: 870000,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 780000 },
    ],
  },
  {
    id: 3,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ 15 اینچی لنوو مدل Ideapad 330 - E",
    alt: "Product",
    price: 70000,
    available: true,
    discount: 10,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 70000 },
    ],
  },
  {
    id: 4,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ 15 لنوو مدل Ideapad 330 - E",
    alt: "Product",
    price: 80000,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 80000 },
    ],
  },
  {
    id: 5,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ  مدل Ideapad 330 - E",
    alt: "Product",
    price: 130000,
    discount: 15,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 130000 },
    ],
  },
  {
    id: 6,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ  مدل Ideapad 330 - E",
    alt: "Product",
    price: 130000,
    discount: 15,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 130000 },
    ],
  },
];
