// import { TranslationKeysAll, useTranslate } from "hooks";
import Head from "next/head";
import { useRouter } from "next/router";

const Helmet: React.FC<{ title?: string; children: React.ReactNode }> = ({
  title,
  children,
}): React.ReactElement => {
  const { pathname } = useRouter();
  //   const { t } = useTranslate();

  const tit = pathname === "/" ? "صفحه نخست" : pathname;
  const res = tit ? "لوله" + " | " + tit : "لوله";

  return (
    <>
      <Head>
        <title>{res}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Helmet;
