import Footer from "components/Footer";
import Header from "components/Header";
import CartDetails from "components/Header/CartDetails";
import { useMediaQuery } from "hooks";
import { TKey } from "interfaces";
import Head from "next/head";
import { useRouter } from "next/router";
import { useTranslation } from "react-i18next";

export default function Layout({
  children,
  title,
  content = "Generated by create next app",
}: {
  children: React.ReactNode;
  title?: string;
  content?: string;
}) {
  const { t } = useTranslation();
  const { pathname } = useRouter();
  const matches = useMediaQuery("(min-width: 768px)");

  const tit =
    pathname === "/"
      ? t("home")
      : t("home") + " | " + t(pathname?.split("/")[1] as TKey);
  return (
    <>
      <Head>
        <title>{tit}</title>
        <meta name="description" content={content} />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {children}
      <Footer />
      {!matches && (
        <footer className="sticky bottom-0 bg-white z-40 border-t">
          <div className="grid grid-cols-3">
            <CartDetails />
          </div>
        </footer>
      )}
    </>
  );
}
